version: "3.7"

services:
  db:
      image: mysql
      restart: always
      command: --max_allowed_packet=67108864
      environment:
          MYSQL_DATABASE: 'items'
          MYSQL_USER: 'user'
          MYSQL_PASSWORD: 'password'
          MYSQL_ROOT_PASSWORD: 'password'
      volumes:
       - db_data:/var/lib/mysql
      ports:
       - '3306:3306'
      security_opt:
       - seccomp:unconfined
volumes:
  db_data: