name: Tests on Pull Request

on: push

jobs:

  tests:
    name: Tests
    runs-on: ubuntu-18.04
    steps:
      - name: Run MySQL Instance 
        run: docker-compose up -d --build
      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install pip==20.2
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest